// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: osmi.proto

package osmi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ TICKETS ============
type TicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`          // UUID del evento (requerido)
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // UUID del usuario/customer (requerido)
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // UUID de la categoría (requerido)
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                      // Cantidad de tickets (default: 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketRequest) Reset() {
	*x = TicketRequest{}
	mi := &file_osmi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRequest) ProtoMessage() {}

func (x *TicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRequest.ProtoReflect.Descriptor instead.
func (*TicketRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{0}
}

func (x *TicketRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TicketRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *TicketRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`             // UUID público del ticket
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // available, reserved, sold, used, cancelled
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                     // Código único del ticket
	QrCodeUrl     string                 `protobuf:"bytes,4,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"`        // URL del QR code
	EventName     string                 `protobuf:"bytes,5,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`          // Nombre del evento
	EventDate     string                 `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`          // Fecha del evento
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`                             // Ubicación del evento
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`                                 // Precio del ticket
	CategoryName  string                 `protobuf:"bytes,9,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // Nombre de la categoría
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketResponse) Reset() {
	*x = TicketResponse{}
	mi := &file_osmi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponse) ProtoMessage() {}

func (x *TicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponse.ProtoReflect.Descriptor instead.
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{1}
}

func (x *TicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TicketResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *TicketResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TicketResponse) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *TicketResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TicketResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *TicketResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TicketListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketResponse      `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketListResponse) Reset() {
	*x = TicketListResponse{}
	mi := &file_osmi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListResponse) ProtoMessage() {}

func (x *TicketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListResponse.ProtoReflect.Descriptor instead.
func (*TicketListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{2}
}

func (x *TicketListResponse) GetTickets() []*TicketResponse {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *TicketListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ============ CUSTOMERS ============
type CustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // (requerido)
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // (requerido)
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"` // (opcional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	mi := &file_osmi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CustomerLookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*CustomerLookup_Id
	//	*CustomerLookup_PublicId
	//	*CustomerLookup_Email
	Lookup        isCustomerLookup_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerLookup) Reset() {
	*x = CustomerLookup{}
	mi := &file_osmi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLookup) ProtoMessage() {}

func (x *CustomerLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLookup.ProtoReflect.Descriptor instead.
func (*CustomerLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerLookup) GetLookup() isCustomerLookup_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *CustomerLookup) GetId() int32 {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *CustomerLookup) GetPublicId() string {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_PublicId); ok {
			return x.PublicId
		}
	}
	return ""
}

func (x *CustomerLookup) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*CustomerLookup_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isCustomerLookup_Lookup interface {
	isCustomerLookup_Lookup()
}

type CustomerLookup_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"` // ID interno
}

type CustomerLookup_PublicId struct {
	PublicId string `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3,oneof"` // UUID público
}

type CustomerLookup_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"` // Email del cliente
}

func (*CustomerLookup_Id) isCustomerLookup_Lookup() {}

func (*CustomerLookup_PublicId) isCustomerLookup_Lookup() {}

func (*CustomerLookup_Email) isCustomerLookup_Lookup() {}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_osmi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CustomerResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CustomerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CustomerResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ============ USERS ============
type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // (requerido)
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // (requerido)
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // (requerido)
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`         // customer, organizer, admin (default: customer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_osmi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{6}
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID público
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // active, inactive, pending
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_osmi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID público
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLookup) Reset() {
	*x = UserLookup{}
	mi := &file_osmi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLookup) ProtoMessage() {}

func (x *UserLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLookup.ProtoReflect.Descriptor instead.
func (*UserLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{8}
}

func (x *UserLookup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ============ EVENTS ============
type EventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                 // (requerido)
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                   // (opcional)
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"` // (opcional)
	StartDate        string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                      // (requerido) Formato RFC3339
	EndDate          string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                            // (requerido) Formato RFC3339
	Location         string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`                                         // (requerido)
	VenueDetails     string                 `protobuf:"bytes,7,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`             // (opcional)
	Category         string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`                                         // (opcional)
	Tags             []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`                                                 // Lista de tags
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                       // (default: true)
	IsPublished      bool                   `protobuf:"varint,11,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`              // (default: false)
	ImageUrl         string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                        // (opcional)
	BannerUrl        string                 `protobuf:"bytes,13,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`                     // (opcional)
	MaxAttendees     int32                  `protobuf:"varint,14,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`           // (opcional)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_osmi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{9}
}

func (x *EventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventRequest) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventRequest) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventRequest) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

type EventResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicId         string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	StartDate        string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Formato RFC3339
	EndDate          string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Formato RFC3339
	Location         string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	VenueDetails     string                 `protobuf:"bytes,8,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`
	Category         string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Tags             []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	IsActive         bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPublished      bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,13,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl        string                 `protobuf:"bytes,14,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	MaxAttendees     int32                  `protobuf:"varint,15,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	TotalTickets     int32                  `protobuf:"varint,16,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"` // Total de tickets disponibles
	TicketsSold      int32                  `protobuf:"varint,17,opt,name=tickets_sold,json=ticketsSold,proto3" json:"tickets_sold,omitempty"`    // Tickets vendidos
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_osmi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{10}
}

func (x *EventResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *EventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventResponse) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventResponse) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventResponse) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventResponse) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventResponse) GetTotalTickets() int32 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *EventResponse) GetTicketsSold() int32 {
	if x != nil {
		return x.TicketsSold
	}
	return 0
}

func (x *EventResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EventLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLookup) Reset() {
	*x = EventLookup{}
	mi := &file_osmi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLookup) ProtoMessage() {}

func (x *EventLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLookup.ProtoReflect.Descriptor instead.
func (*EventLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{11}
}

func (x *EventLookup) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type EventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventResponse       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_osmi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResponse.ProtoReflect.Descriptor instead.
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{12}
}

func (x *EventListResponse) GetEvents() []*EventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ============ CATEGORIES ============
// NUEVO: Request para crear categoría
type CategoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                       // UUID del evento (requerido)
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                            // (requerido)
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                              // (opcional)
	Price              float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                                                        // (requerido, >= 0)
	QuantityAvailable  int32                  `protobuf:"varint,5,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`        // (requerido, >= 0)
	MaxTicketsPerOrder int32                  `protobuf:"varint,6,opt,name=max_tickets_per_order,json=maxTicketsPerOrder,proto3" json:"max_tickets_per_order,omitempty"` // (default: 10)
	SalesStart         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sales_start,json=salesStart,proto3" json:"sales_start,omitempty"`                              // (default: now)
	SalesEnd           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sales_end,json=salesEnd,proto3" json:"sales_end,omitempty"`                                    // (opcional)
	Benefits           []string               `protobuf:"bytes,9,rep,name=benefits,proto3" json:"benefits,omitempty"`                                                    // Lista de beneficios
	IsActive           bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                                  // (default: true)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_osmi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{13}
}

func (x *CategoryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CategoryRequest) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CategoryRequest) GetMaxTicketsPerOrder() int32 {
	if x != nil {
		return x.MaxTicketsPerOrder
	}
	return 0
}

func (x *CategoryRequest) GetSalesStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesStart
	}
	return nil
}

func (x *CategoryRequest) GetSalesEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesEnd
	}
	return nil
}

func (x *CategoryRequest) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *CategoryRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// NUEVO: Response para categoría creada
type CategoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PublicId           string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`                                    // UUID público
	EventId            string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                       // UUID del evento
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                            // Nombre de la categoría
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                              // Descripción
	Price              float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                                        // Precio
	QuantityAvailable  int32                  `protobuf:"varint,6,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`        // Cantidad disponible
	QuantitySold       int32                  `protobuf:"varint,7,opt,name=quantity_sold,json=quantitySold,proto3" json:"quantity_sold,omitempty"`                       // Cantidad vendida (siempre 0 al crear)
	MaxTicketsPerOrder int32                  `protobuf:"varint,8,opt,name=max_tickets_per_order,json=maxTicketsPerOrder,proto3" json:"max_tickets_per_order,omitempty"` // Máximo por orden
	SalesStart         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sales_start,json=salesStart,proto3" json:"sales_start,omitempty"`
	SalesEnd           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sales_end,json=salesEnd,proto3" json:"sales_end,omitempty"`
	Benefits           []string               `protobuf:"bytes,11,rep,name=benefits,proto3" json:"benefits,omitempty"`                  // Beneficios
	IsActive           bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // Estado activo
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_osmi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{14}
}

func (x *CategoryResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CategoryResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CategoryResponse) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CategoryResponse) GetQuantitySold() int32 {
	if x != nil {
		return x.QuantitySold
	}
	return 0
}

func (x *CategoryResponse) GetMaxTicketsPerOrder() int32 {
	if x != nil {
		return x.MaxTicketsPerOrder
	}
	return 0
}

func (x *CategoryResponse) GetSalesStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesStart
	}
	return nil
}

func (x *CategoryResponse) GetSalesEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesEnd
	}
	return nil
}

func (x *CategoryResponse) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *CategoryResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CategoryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CategoryResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Existente: Response para listar categorías de evento
type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryResponse    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventPublicId string                 `protobuf:"bytes,3,opt,name=event_public_id,json=eventPublicId,proto3" json:"event_public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_osmi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryListResponse) GetCategories() []*CategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CategoryListResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CategoryListResponse) GetEventPublicId() string {
	if x != nil {
		return x.EventPublicId
	}
	return ""
}

// ============ COMMON TYPES ============
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_osmi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{16}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_osmi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{17}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// ============ HEALTH CHECK ============
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // healthy, unhealthy
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_osmi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ============ COMMON ============
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_osmi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{19}
}

var File_osmi_proto protoreflect.FileDescriptor

const file_osmi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"osmi.proto\x12\x04osmi\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\rTicketRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"\xc9\x02\n" +
	"\x0eTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1e\n" +
	"\vqr_code_url\x18\x04 \x01(\tR\tqrCodeUrl\x12\x1d\n" +
	"\n" +
	"event_name\x18\x05 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"event_date\x18\x06 \x01(\tR\teventDate\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12#\n" +
	"\rcategory_name\x18\t \x01(\tR\fcategoryName\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x12TicketListResponse\x12.\n" +
	"\atickets\x18\x01 \x03(\v2\x14.osmi.TicketResponseR\atickets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Q\n" +
	"\x0fCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"c\n" +
	"\x0eCustomerLookup\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x12\x1d\n" +
	"\tpublic_id\x18\x02 \x01(\tH\x00R\bpublicId\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\b\n" +
	"\x06lookup\"\xf5\x01\n" +
	"\x10CustomerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xb8\x01\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"%\n" +
	"\n" +
	"UserLookup\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbd\x03\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\a \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\v \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\r \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x0e \x01(\x05R\fmaxAttendees\"\x99\x05\n" +
	"\rEventResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\b \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\r \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x0e \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x0f \x01(\x05R\fmaxAttendees\x12#\n" +
	"\rtotal_tickets\x18\x10 \x01(\x05R\ftotalTickets\x12!\n" +
	"\ftickets_sold\x18\x11 \x01(\x05R\vticketsSold\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\vEventLookup\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"a\n" +
	"\x11EventListResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.osmi.EventResponseR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x89\x03\n" +
	"\x0fCategoryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12-\n" +
	"\x12quantity_available\x18\x05 \x01(\x05R\x11quantityAvailable\x121\n" +
	"\x15max_tickets_per_order\x18\x06 \x01(\x05R\x12maxTicketsPerOrder\x12;\n" +
	"\vsales_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"salesStart\x127\n" +
	"\tsales_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bsalesEnd\x12\x1a\n" +
	"\bbenefits\x18\t \x03(\tR\bbenefits\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\xc2\x04\n" +
	"\x10CategoryResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12-\n" +
	"\x12quantity_available\x18\x06 \x01(\x05R\x11quantityAvailable\x12#\n" +
	"\rquantity_sold\x18\a \x01(\x05R\fquantitySold\x121\n" +
	"\x15max_tickets_per_order\x18\b \x01(\x05R\x12maxTicketsPerOrder\x12;\n" +
	"\vsales_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"salesStart\x127\n" +
	"\tsales_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bsalesEnd\x12\x1a\n" +
	"\bbenefits\x18\v \x03(\tR\bbenefits\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x01\n" +
	"\x14CategoryListResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.osmi.CategoryResponseR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12&\n" +
	"\x0fevent_public_id\x18\x03 \x01(\tR\reventPublicId\"\x86\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\"G\n" +
	"\vCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x96\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\a\n" +
	"\x05Empty2\x9b\a\n" +
	"\vOsmiService\x12N\n" +
	"\fCreateTicket\x12\x13.osmi.TicketRequest\x1a\x14.osmi.TicketResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/tickets\x12[\n" +
	"\vListTickets\x12\x10.osmi.UserLookup\x1a\x18.osmi.TicketListResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/users/{user_id}/tickets\x12V\n" +
	"\x0eCreateCustomer\x12\x15.osmi.CustomerRequest\x1a\x16.osmi.CustomerResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/customers\x12T\n" +
	"\vGetCustomer\x12\x14.osmi.CustomerLookup\x1a\x16.osmi.CustomerResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/customers/{id}\x12F\n" +
	"\n" +
	"CreateUser\x12\x11.osmi.UserRequest\x1a\x12.osmi.UserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12J\n" +
	"\vCreateEvent\x12\x12.osmi.EventRequest\x1a\x13.osmi.EventResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/events\x12O\n" +
	"\bGetEvent\x12\x11.osmi.EventLookup\x1a\x13.osmi.EventResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/events/{public_id}\x12C\n" +
	"\n" +
	"ListEvents\x12\v.osmi.Empty\x1a\x17.osmi.EventListResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/events\x12W\n" +
	"\x0eCreateCategory\x12\x15.osmi.CategoryRequest\x1a\x16.osmi.CategoryResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/categories\x12k\n" +
	"\x12GetEventCategories\x12\x11.osmi.EventLookup\x1a\x1a.osmi.CategoryListResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/events/{public_id}/categories\x12A\n" +
	"\vHealthCheck\x12\v.osmi.Empty\x1a\x14.osmi.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB2Z0github.com/franciscozamorau/osmi-server/gen;osmib\x06proto3"

var (
	file_osmi_proto_rawDescOnce sync.Once
	file_osmi_proto_rawDescData []byte
)

func file_osmi_proto_rawDescGZIP() []byte {
	file_osmi_proto_rawDescOnce.Do(func() {
		file_osmi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)))
	})
	return file_osmi_proto_rawDescData
}

var file_osmi_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_osmi_proto_goTypes = []any{
	(*TicketRequest)(nil),         // 0: osmi.TicketRequest
	(*TicketResponse)(nil),        // 1: osmi.TicketResponse
	(*TicketListResponse)(nil),    // 2: osmi.TicketListResponse
	(*CustomerRequest)(nil),       // 3: osmi.CustomerRequest
	(*CustomerLookup)(nil),        // 4: osmi.CustomerLookup
	(*CustomerResponse)(nil),      // 5: osmi.CustomerResponse
	(*UserRequest)(nil),           // 6: osmi.UserRequest
	(*UserResponse)(nil),          // 7: osmi.UserResponse
	(*UserLookup)(nil),            // 8: osmi.UserLookup
	(*EventRequest)(nil),          // 9: osmi.EventRequest
	(*EventResponse)(nil),         // 10: osmi.EventResponse
	(*EventLookup)(nil),           // 11: osmi.EventLookup
	(*EventListResponse)(nil),     // 12: osmi.EventListResponse
	(*CategoryRequest)(nil),       // 13: osmi.CategoryRequest
	(*CategoryResponse)(nil),      // 14: osmi.CategoryResponse
	(*CategoryListResponse)(nil),  // 15: osmi.CategoryListResponse
	(*Address)(nil),               // 16: osmi.Address
	(*Coordinates)(nil),           // 17: osmi.Coordinates
	(*HealthResponse)(nil),        // 18: osmi.HealthResponse
	(*Empty)(nil),                 // 19: osmi.Empty
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_osmi_proto_depIdxs = []int32{
	20, // 0: osmi.TicketResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: osmi.TicketListResponse.tickets:type_name -> osmi.TicketResponse
	20, // 2: osmi.CustomerResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: osmi.CustomerResponse.updated_at:type_name -> google.protobuf.Timestamp
	20, // 4: osmi.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: osmi.EventResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 6: osmi.EventResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 7: osmi.EventListResponse.events:type_name -> osmi.EventResponse
	20, // 8: osmi.CategoryRequest.sales_start:type_name -> google.protobuf.Timestamp
	20, // 9: osmi.CategoryRequest.sales_end:type_name -> google.protobuf.Timestamp
	20, // 10: osmi.CategoryResponse.sales_start:type_name -> google.protobuf.Timestamp
	20, // 11: osmi.CategoryResponse.sales_end:type_name -> google.protobuf.Timestamp
	20, // 12: osmi.CategoryResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 13: osmi.CategoryResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 14: osmi.CategoryListResponse.categories:type_name -> osmi.CategoryResponse
	20, // 15: osmi.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 16: osmi.OsmiService.CreateTicket:input_type -> osmi.TicketRequest
	8,  // 17: osmi.OsmiService.ListTickets:input_type -> osmi.UserLookup
	3,  // 18: osmi.OsmiService.CreateCustomer:input_type -> osmi.CustomerRequest
	4,  // 19: osmi.OsmiService.GetCustomer:input_type -> osmi.CustomerLookup
	6,  // 20: osmi.OsmiService.CreateUser:input_type -> osmi.UserRequest
	9,  // 21: osmi.OsmiService.CreateEvent:input_type -> osmi.EventRequest
	11, // 22: osmi.OsmiService.GetEvent:input_type -> osmi.EventLookup
	19, // 23: osmi.OsmiService.ListEvents:input_type -> osmi.Empty
	13, // 24: osmi.OsmiService.CreateCategory:input_type -> osmi.CategoryRequest
	11, // 25: osmi.OsmiService.GetEventCategories:input_type -> osmi.EventLookup
	19, // 26: osmi.OsmiService.HealthCheck:input_type -> osmi.Empty
	1,  // 27: osmi.OsmiService.CreateTicket:output_type -> osmi.TicketResponse
	2,  // 28: osmi.OsmiService.ListTickets:output_type -> osmi.TicketListResponse
	5,  // 29: osmi.OsmiService.CreateCustomer:output_type -> osmi.CustomerResponse
	5,  // 30: osmi.OsmiService.GetCustomer:output_type -> osmi.CustomerResponse
	7,  // 31: osmi.OsmiService.CreateUser:output_type -> osmi.UserResponse
	10, // 32: osmi.OsmiService.CreateEvent:output_type -> osmi.EventResponse
	10, // 33: osmi.OsmiService.GetEvent:output_type -> osmi.EventResponse
	12, // 34: osmi.OsmiService.ListEvents:output_type -> osmi.EventListResponse
	14, // 35: osmi.OsmiService.CreateCategory:output_type -> osmi.CategoryResponse
	15, // 36: osmi.OsmiService.GetEventCategories:output_type -> osmi.CategoryListResponse
	18, // 37: osmi.OsmiService.HealthCheck:output_type -> osmi.HealthResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_osmi_proto_init() }
func file_osmi_proto_init() {
	if File_osmi_proto != nil {
		return
	}
	file_osmi_proto_msgTypes[4].OneofWrappers = []any{
		(*CustomerLookup_Id)(nil),
		(*CustomerLookup_PublicId)(nil),
		(*CustomerLookup_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osmi_proto_goTypes,
		DependencyIndexes: file_osmi_proto_depIdxs,
		MessageInfos:      file_osmi_proto_msgTypes,
	}.Build()
	File_osmi_proto = out.File
	file_osmi_proto_goTypes = nil
	file_osmi_proto_depIdxs = nil
}
