// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: osmi.proto

package osmi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ TICKETS ============
type TicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`          // UUID del evento
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // UUID del usuario/customer
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // UUID de la categoría
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketRequest) Reset() {
	*x = TicketRequest{}
	mi := &file_osmi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRequest) ProtoMessage() {}

func (x *TicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRequest.ProtoReflect.Descriptor instead.
func (*TicketRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{0}
}

func (x *TicketRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TicketRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type TicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`      // UUID público del ticket
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                          // available, reserved, sold, used, cancelled
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                              // Código único del ticket
	QrCodeUrl     string                 `protobuf:"bytes,4,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"` // URL del QR code
	EventName     string                 `protobuf:"bytes,5,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`   // Nombre del evento (para UI)
	EventDate     string                 `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`   // Fecha del evento
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`                      // Ubicación del evento
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketResponse) Reset() {
	*x = TicketResponse{}
	mi := &file_osmi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponse) ProtoMessage() {}

func (x *TicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponse.ProtoReflect.Descriptor instead.
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{1}
}

func (x *TicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TicketResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *TicketResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TicketResponse) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *TicketResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type TicketListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketResponse      `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketListResponse) Reset() {
	*x = TicketListResponse{}
	mi := &file_osmi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListResponse) ProtoMessage() {}

func (x *TicketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListResponse.ProtoReflect.Descriptor instead.
func (*TicketListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{2}
}

func (x *TicketListResponse) GetTickets() []*TicketResponse {
	if x != nil {
		return x.Tickets
	}
	return nil
}

// ============ CUSTOMERS ============
type CustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // Formato YYYY-MM-DD
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                              // JSON string
	Preferences   string                 `protobuf:"bytes,6,opt,name=preferences,proto3" json:"preferences,omitempty"`                      // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	mi := &file_osmi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CustomerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CustomerRequest) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type CustomerLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerLookup) Reset() {
	*x = CustomerLookup{}
	mi := &file_osmi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLookup) ProtoMessage() {}

func (x *CustomerLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLookup.ProtoReflect.Descriptor instead.
func (*CustomerLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerLookup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	PublicId      string                 `protobuf:"bytes,5,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`         // JSON string
	Preferences   string                 `protobuf:"bytes,8,opt,name=preferences,proto3" json:"preferences,omitempty"` // JSON string
	LoyaltyPoints int32                  `protobuf:"varint,9,opt,name=loyalty_points,json=loyaltyPoints,proto3" json:"loyalty_points,omitempty"`
	IsVerified    bool                   `protobuf:"varint,10,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerResponse) Reset() {
	*x = CustomerResponse{}
	mi := &file_osmi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerResponse) ProtoMessage() {}

func (x *CustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerResponse.ProtoReflect.Descriptor instead.
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CustomerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CustomerResponse) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CustomerResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CustomerResponse) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *CustomerResponse) GetLoyaltyPoints() int32 {
	if x != nil {
		return x.LoyaltyPoints
	}
	return 0
}

func (x *CustomerResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *CustomerResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CustomerResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ============ USERS ============
type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // Para autenticación futura
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`         // customer, organizer, admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_osmi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{6}
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID público
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // active, inactive
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_osmi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID público
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLookup) Reset() {
	*x = UserLookup{}
	mi := &file_osmi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLookup) ProtoMessage() {}

func (x *UserLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLookup.ProtoReflect.Descriptor instead.
func (*UserLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{8}
}

func (x *UserLookup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ============ EVENTS ============
type EventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	StartDate        string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // RFC3339 format
	EndDate          string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // RFC3339 format
	Location         string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	VenueDetails     string                 `protobuf:"bytes,7,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`
	Category         string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Tags             string                 `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"` // JSON array string
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPublished      bool                   `protobuf:"varint,11,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl        string                 `protobuf:"bytes,13,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	MaxAttendees     int32                  `protobuf:"varint,14,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	Latitude         float64                `protobuf:"fixed64,15,opt,name=latitude,proto3" json:"latitude,omitempty"`                         // Para coordenadas
	Longitude        float64                `protobuf:"fixed64,16,opt,name=longitude,proto3" json:"longitude,omitempty"`                       // Para coordenadas
	OrganizerId      int32                  `protobuf:"varint,17,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"` // ID del organizador
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_osmi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{9}
}

func (x *EventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventRequest) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *EventRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventRequest) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventRequest) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EventRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EventRequest) GetOrganizerId() int32 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

type EventResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicId         string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	StartDate        string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // RFC3339 format
	EndDate          string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // RFC3339 format
	Location         string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	VenueDetails     string                 `protobuf:"bytes,9,opt,name=venue_details,json=venueDetails,proto3" json:"venue_details,omitempty"`
	Category         string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	Tags             string                 `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"` // JSON array string
	IsActive         bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPublished      bool                   `protobuf:"varint,13,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,14,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl        string                 `protobuf:"bytes,15,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	MaxAttendees     int32                  `protobuf:"varint,16,opt,name=max_attendees,json=maxAttendees,proto3" json:"max_attendees,omitempty"`
	Latitude         float64                `protobuf:"fixed64,17,opt,name=latitude,proto3" json:"latitude,omitempty"`   // Para coordenadas
	Longitude        float64                `protobuf:"fixed64,18,opt,name=longitude,proto3" json:"longitude,omitempty"` // Para coordenadas
	OrganizerId      int32                  `protobuf:"varint,19,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_osmi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{10}
}

func (x *EventResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *EventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventResponse) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *EventResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventResponse) GetVenueDetails() string {
	if x != nil {
		return x.VenueDetails
	}
	return ""
}

func (x *EventResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventResponse) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *EventResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EventResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *EventResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventResponse) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *EventResponse) GetMaxAttendees() int32 {
	if x != nil {
		return x.MaxAttendees
	}
	return 0
}

func (x *EventResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EventResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EventResponse) GetOrganizerId() int32 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *EventResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EventLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLookup) Reset() {
	*x = EventLookup{}
	mi := &file_osmi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLookup) ProtoMessage() {}

func (x *EventLookup) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLookup.ProtoReflect.Descriptor instead.
func (*EventLookup) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{11}
}

func (x *EventLookup) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type EventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventResponse       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_osmi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResponse.ProtoReflect.Descriptor instead.
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{12}
}

func (x *EventListResponse) GetEvents() []*EventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

// ============ CATEGORIES ============
type CategoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PublicId           string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // UUID público
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price              float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	QuantityAvailable  int32                  `protobuf:"varint,5,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	QuantitySold       int32                  `protobuf:"varint,6,opt,name=quantity_sold,json=quantitySold,proto3" json:"quantity_sold,omitempty"`
	MaxTicketsPerOrder int32                  `protobuf:"varint,7,opt,name=max_tickets_per_order,json=maxTicketsPerOrder,proto3" json:"max_tickets_per_order,omitempty"`
	SalesStart         string                 `protobuf:"bytes,8,opt,name=sales_start,json=salesStart,proto3" json:"sales_start,omitempty"` // RFC3339 format
	SalesEnd           string                 `protobuf:"bytes,9,opt,name=sales_end,json=salesEnd,proto3" json:"sales_end,omitempty"`       // RFC3339 format
	IsActive           bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Benefits           []string               `protobuf:"bytes,11,rep,name=benefits,proto3" json:"benefits,omitempty"` // Beneficios incluidos
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_osmi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{13}
}

func (x *CategoryResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CategoryResponse) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CategoryResponse) GetQuantitySold() int32 {
	if x != nil {
		return x.QuantitySold
	}
	return 0
}

func (x *CategoryResponse) GetMaxTicketsPerOrder() int32 {
	if x != nil {
		return x.MaxTicketsPerOrder
	}
	return 0
}

func (x *CategoryResponse) GetSalesStart() string {
	if x != nil {
		return x.SalesStart
	}
	return ""
}

func (x *CategoryResponse) GetSalesEnd() string {
	if x != nil {
		return x.SalesEnd
	}
	return ""
}

func (x *CategoryResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CategoryResponse) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryResponse    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_osmi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{14}
}

func (x *CategoryListResponse) GetCategories() []*CategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

// ============ TRANSACTIONS ============
// (Para futura implementación)
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`          // UUID del customer
	TicketIds     []string               `protobuf:"bytes,2,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`             // UUIDs de tickets
	PromotionCode string                 `protobuf:"bytes,3,opt,name=promotion_code,json=promotionCode,proto3" json:"promotion_code,omitempty"` // Código de promoción opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_osmi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *TransactionRequest) GetTicketIds() []string {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

func (x *TransactionRequest) GetPromotionCode() string {
	if x != nil {
		return x.PromotionCode
	}
	return ""
}

type TransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // UUID público
	Amount          float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DiscountAmount  float64                `protobuf:"fixed64,3,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount     float64                `protobuf:"fixed64,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                            // pending, completed, failed
	StripeSessionId string                 `protobuf:"bytes,6,opt,name=stripe_session_id,json=stripeSessionId,proto3" json:"stripe_session_id,omitempty"` // Para integración Stripe
	ReceiptUrl      string                 `protobuf:"bytes,7,opt,name=receipt_url,json=receiptUrl,proto3" json:"receipt_url,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_osmi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *TransactionResponse) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *TransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionResponse) GetStripeSessionId() string {
	if x != nil {
		return x.StripeSessionId
	}
	return ""
}

func (x *TransactionResponse) GetReceiptUrl() string {
	if x != nil {
		return x.ReceiptUrl
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// ============ COMMON ============
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_osmi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_osmi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_osmi_proto_rawDescGZIP(), []int{17}
}

var File_osmi_proto protoreflect.FileDescriptor

const file_osmi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"osmi.proto\x12\x04osmi\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\rTicketRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\"\xd3\x01\n" +
	"\x0eTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1e\n" +
	"\vqr_code_url\x18\x04 \x01(\tR\tqrCodeUrl\x12\x1d\n" +
	"\n" +
	"event_name\x18\x05 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"event_date\x18\x06 \x01(\tR\teventDate\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\"D\n" +
	"\x12TicketListResponse\x12.\n" +
	"\atickets\x18\x01 \x03(\v2\x14.osmi.TicketResponseR\atickets\"\xb1\x01\n" +
	"\x0fCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12 \n" +
	"\vpreferences\x18\x06 \x01(\tR\vpreferences\" \n" +
	"\x0eCustomerLookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xe5\x02\n" +
	"\x10CustomerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1b\n" +
	"\tpublic_id\x18\x05 \x01(\tR\bpublicId\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12 \n" +
	"\vpreferences\x18\b \x01(\tR\vpreferences\x12%\n" +
	"\x0eloyalty_points\x18\t \x01(\x05R\rloyaltyPoints\x12\x1f\n" +
	"\vis_verified\x18\n" +
	" \x01(\bR\n" +
	"isVerified\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"g\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\x9c\x01\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"%\n" +
	"\n" +
	"UserLookup\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9a\x04\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\a \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\t \x01(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\v \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\r \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x0e \x01(\x05R\fmaxAttendees\x12\x1a\n" +
	"\blatitude\x18\x0f \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x10 \x01(\x01R\tlongitude\x12!\n" +
	"\forganizer_id\x18\x11 \x01(\x05R\vorganizerId\"\x86\x05\n" +
	"\rEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x05 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12#\n" +
	"\rvenue_details\x18\t \x01(\tR\fvenueDetails\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\v \x01(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12!\n" +
	"\fis_published\x18\r \x01(\bR\visPublished\x12\x1b\n" +
	"\timage_url\x18\x0e \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x0f \x01(\tR\tbannerUrl\x12#\n" +
	"\rmax_attendees\x18\x10 \x01(\x05R\fmaxAttendees\x12\x1a\n" +
	"\blatitude\x18\x11 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x12 \x01(\x01R\tlongitude\x12!\n" +
	"\forganizer_id\x18\x13 \x01(\x05R\vorganizerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\"*\n" +
	"\vEventLookup\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"@\n" +
	"\x11EventListResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.osmi.EventResponseR\x06events\"\xf9\x02\n" +
	"\x10CategoryResponse\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12-\n" +
	"\x12quantity_available\x18\x05 \x01(\x05R\x11quantityAvailable\x12#\n" +
	"\rquantity_sold\x18\x06 \x01(\x05R\fquantitySold\x121\n" +
	"\x15max_tickets_per_order\x18\a \x01(\x05R\x12maxTicketsPerOrder\x12\x1f\n" +
	"\vsales_start\x18\b \x01(\tR\n" +
	"salesStart\x12\x1b\n" +
	"\tsales_end\x18\t \x01(\tR\bsalesEnd\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x1a\n" +
	"\bbenefits\x18\v \x03(\tR\bbenefits\"N\n" +
	"\x14CategoryListResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.osmi.CategoryResponseR\n" +
	"categories\"{\n" +
	"\x12TransactionRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\x02 \x03(\tR\tticketIds\x12%\n" +
	"\x0epromotion_code\x18\x03 \x01(\tR\rpromotionCode\"\xa4\x02\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12'\n" +
	"\x0fdiscount_amount\x18\x03 \x01(\x01R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x01R\vfinalAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x11stripe_session_id\x18\x06 \x01(\tR\x0fstripeSessionId\x12\x1f\n" +
	"\vreceipt_url\x18\a \x01(\tR\n" +
	"receiptUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\a\n" +
	"\x05Empty2\xff\x05\n" +
	"\vOsmiService\x12N\n" +
	"\fCreateTicket\x12\x13.osmi.TicketRequest\x1a\x14.osmi.TicketResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/tickets\x12[\n" +
	"\vListTickets\x12\x10.osmi.UserLookup\x1a\x18.osmi.TicketListResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/users/{user_id}/tickets\x12V\n" +
	"\x0eCreateCustomer\x12\x15.osmi.CustomerRequest\x1a\x16.osmi.CustomerResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/customers\x12T\n" +
	"\vGetCustomer\x12\x14.osmi.CustomerLookup\x1a\x16.osmi.CustomerResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/customers/{id}\x12F\n" +
	"\n" +
	"CreateUser\x12\x11.osmi.UserRequest\x1a\x12.osmi.UserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12J\n" +
	"\vCreateEvent\x12\x12.osmi.EventRequest\x1a\x13.osmi.EventResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/events\x12O\n" +
	"\bGetEvent\x12\x11.osmi.EventLookup\x1a\x13.osmi.EventResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/events/{public_id}\x12C\n" +
	"\n" +
	"ListEvents\x12\v.osmi.Empty\x1a\x17.osmi.EventListResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/events\x12k\n" +
	"\x12GetEventCategories\x12\x11.osmi.EventLookup\x1a\x1a.osmi.CategoryListResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/events/{public_id}/categoriesB1Z/github.com/franciscozamorau/osmi-proto/gen;osmib\x06proto3"

var (
	file_osmi_proto_rawDescOnce sync.Once
	file_osmi_proto_rawDescData []byte
)

func file_osmi_proto_rawDescGZIP() []byte {
	file_osmi_proto_rawDescOnce.Do(func() {
		file_osmi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)))
	})
	return file_osmi_proto_rawDescData
}

var file_osmi_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_osmi_proto_goTypes = []any{
	(*TicketRequest)(nil),        // 0: osmi.TicketRequest
	(*TicketResponse)(nil),       // 1: osmi.TicketResponse
	(*TicketListResponse)(nil),   // 2: osmi.TicketListResponse
	(*CustomerRequest)(nil),      // 3: osmi.CustomerRequest
	(*CustomerLookup)(nil),       // 4: osmi.CustomerLookup
	(*CustomerResponse)(nil),     // 5: osmi.CustomerResponse
	(*UserRequest)(nil),          // 6: osmi.UserRequest
	(*UserResponse)(nil),         // 7: osmi.UserResponse
	(*UserLookup)(nil),           // 8: osmi.UserLookup
	(*EventRequest)(nil),         // 9: osmi.EventRequest
	(*EventResponse)(nil),        // 10: osmi.EventResponse
	(*EventLookup)(nil),          // 11: osmi.EventLookup
	(*EventListResponse)(nil),    // 12: osmi.EventListResponse
	(*CategoryResponse)(nil),     // 13: osmi.CategoryResponse
	(*CategoryListResponse)(nil), // 14: osmi.CategoryListResponse
	(*TransactionRequest)(nil),   // 15: osmi.TransactionRequest
	(*TransactionResponse)(nil),  // 16: osmi.TransactionResponse
	(*Empty)(nil),                // 17: osmi.Empty
}
var file_osmi_proto_depIdxs = []int32{
	1,  // 0: osmi.TicketListResponse.tickets:type_name -> osmi.TicketResponse
	10, // 1: osmi.EventListResponse.events:type_name -> osmi.EventResponse
	13, // 2: osmi.CategoryListResponse.categories:type_name -> osmi.CategoryResponse
	0,  // 3: osmi.OsmiService.CreateTicket:input_type -> osmi.TicketRequest
	8,  // 4: osmi.OsmiService.ListTickets:input_type -> osmi.UserLookup
	3,  // 5: osmi.OsmiService.CreateCustomer:input_type -> osmi.CustomerRequest
	4,  // 6: osmi.OsmiService.GetCustomer:input_type -> osmi.CustomerLookup
	6,  // 7: osmi.OsmiService.CreateUser:input_type -> osmi.UserRequest
	9,  // 8: osmi.OsmiService.CreateEvent:input_type -> osmi.EventRequest
	11, // 9: osmi.OsmiService.GetEvent:input_type -> osmi.EventLookup
	17, // 10: osmi.OsmiService.ListEvents:input_type -> osmi.Empty
	11, // 11: osmi.OsmiService.GetEventCategories:input_type -> osmi.EventLookup
	1,  // 12: osmi.OsmiService.CreateTicket:output_type -> osmi.TicketResponse
	2,  // 13: osmi.OsmiService.ListTickets:output_type -> osmi.TicketListResponse
	5,  // 14: osmi.OsmiService.CreateCustomer:output_type -> osmi.CustomerResponse
	5,  // 15: osmi.OsmiService.GetCustomer:output_type -> osmi.CustomerResponse
	7,  // 16: osmi.OsmiService.CreateUser:output_type -> osmi.UserResponse
	10, // 17: osmi.OsmiService.CreateEvent:output_type -> osmi.EventResponse
	10, // 18: osmi.OsmiService.GetEvent:output_type -> osmi.EventResponse
	12, // 19: osmi.OsmiService.ListEvents:output_type -> osmi.EventListResponse
	14, // 20: osmi.OsmiService.GetEventCategories:output_type -> osmi.CategoryListResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_osmi_proto_init() }
func file_osmi_proto_init() {
	if File_osmi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmi_proto_rawDesc), len(file_osmi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osmi_proto_goTypes,
		DependencyIndexes: file_osmi_proto_depIdxs,
		MessageInfos:      file_osmi_proto_msgTypes,
	}.Build()
	File_osmi_proto = out.File
	file_osmi_proto_goTypes = nil
	file_osmi_proto_depIdxs = nil
}
